### ISSUE TITLE
[FEATURE] And how is it configured so where does the payment go?

### ISSUE THREAD

**Issue by tonymanpro** [ng-web-apis/payment-request#11]
# 🚀 Feature request or observation

### And how is it configured so where does the payment go?

The way to configure the payment to fall into the seller's account should come in the documentation.

**Comment by waterplea** [comment]
Hi @tonymanpro

This library is a wrapper for native Payment Request API so you would need to read on that. We do not have any extra features here, just provide a way to use it with ease in Angular apps.
